describe("Testing fungsional Login",()=>{ 
    beforeEach('akses halaman login account dan add new address', ()=>{
        cy.visit('https://magento.softwaretestingboard.com/customer/account/login/')
        cy.get('#email').type('rohana@mailinator.com')
        cy.get('#pass').type('ROSEhana123')
        cy.get('#send2').click()
        cy.visit('https://magento.softwaretestingboard.com/customer/address/new/')
    })
    it('Mengosongkan semua field', ()=>{ 
        cy.get('#firstname').type('Rohana')
        cy.get('#lastname').type('Rohanna')
        cy.get('#company').clear()
        cy.get('#telephone').clear()
        cy.get('#street_1').clear()
        cy.get('#city').clear()
        cy.get('#region_id').type('Please select a region, state or province.')
        cy.get('#zip').clear()
        cy.get('#country').select('United States')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.get('#telephone-error').should('have.text', 'This is a required field.')
        cy.get('#street_1-error').should('have.text', 'This is a required field.')
        cy.get('#city-error').should('have.text', 'This is a required field.')
        cy.get('#region_id-error').should('have.text', 'Please select an option.')
        cy.get('#zip-error').should('have.text', 'This is a required field.')
    })
    it('memilih salah satu kota pada Dropdown', ()=> {
        cy.get('#firstname').type('Rohana')
        cy.get('#lastname').type('Rohanna')
        cy.get('#company').clear()
        cy.get('#telephone').clear()
        cy.get('#street_1').clear()
        cy.get('#city').clear()
        cy.get('#region_id').select('California')
        cy.get('#zip').clear()
        cy.get('#country').select('United States')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
        cy.get('#telephone-error').should('have.text', 'This is a required field.')
        cy.get('#street_1-error').should('have.text', 'This is a required field.')
        cy.get('#city-error').should('have.text', 'This is a required field.')
        cy.get('#zip-error').should('have.text', 'This is a required field.')
    })
    it('Mengisi form address sesuai dengan ketentuan', ()=> {
        cy.get('#firstname').type('Rohana')
        cy.get('#lastname').type('Rohanna')
        cy.get('#company').type('Bunga Mawar')
        cy.get('#telephone').type('08937483748')
        cy.get('#street_1').type('California Rose Street')
        cy.get('#city').type('california')
        cy.get('#region_id').select('California')
        cy.get('#zip').type('67890')
        cy.get('#country').select('United States')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
       
    })
})