import Registrasi from "../../support/pages/Registrasi"

describe("Registrasi Magento dengan menggunakan POM",()=>{

    beforeEach('mengakses halaman registrasi magento',()=>{
        cy.clearCookies()
        Registrasi.visitreg()
    })
    it('Mengosongkan semua field registrasi',()=>{
        Registrasi.clearFirstname()
        Registrasi.clearLastname()
        Registrasi.clearEmail()
        Registrasi.clearPass()
        Registrasi.clearPassConfirm()
        Registrasi.clickButtonReg()
        Registrasi.errorFirstname()
        Registrasi.errorLastname()
        Registrasi.errorEmail()
        Registrasi.errorPass()
        Registrasi.errorPassConfirm()
    })
    it('Mengisi hanya firstname',()=>{
        Registrasi.InputFirstname('rosehana')
        Registrasi.clearLastname()
        Registrasi.clearEmail()
        Registrasi.clearPass()
        Registrasi.clearPassConfirm()
        Registrasi.clickButtonReg()
        Registrasi.errorLastname()
        Registrasi.errorEmail()
        Registrasi.errorPass()
        Registrasi.errorPassConfirm()
    })
    it('Mengisi hanya field Lastname',()=>{
        Registrasi.clearFirstname()
        Registrasi.InputLastname('hanhanrosros')
        Registrasi.clearEmail()
        Registrasi.clearPass()
        Registrasi.clearPassConfirm()
        Registrasi.clickButtonReg()
        Registrasi.errorFirstname()
        Registrasi.errorEmail()
        Registrasi.errorPass()
        Registrasi.errorPassConfirm()
    })
    it('Mengisi hanya field Email',()=>{
        Registrasi.clearFirstname()
        Registrasi.clearLastname()
        Registrasi.InputEmail('rosehana@mailinator.com')
        Registrasi.clearPass()
        Registrasi.clearPassConfirm()
        Registrasi.clickButtonReg()
        Registrasi.errorFirstname()
        Registrasi.errorLastname()
        Registrasi.errorPass()
        Registrasi.errorPassConfirm()
    })
    it('Mengisi field email dengan invalid email',()=>{
        Registrasi.InputFirstname('rosehana890')
        Registrasi.InputLastname('hanhandamdam')
        Registrasi.InputEmail('rosehana890')
        Registrasi.InputPass('Rosehana890@')
        Registrasi.InputPassConfirm('Rosehana890@')
        Registrasi.clickButtonReg()
        Registrasi.invalidEmail()
    })
    it('Mengisi field Password dengan weak password',()=>{
        Registrasi.InputFirstname('rosehana890')
        Registrasi.InputLastname('hanhandamdam')
        Registrasi.InputEmail('rosehana890@mailinator.com')
        Registrasi.InputPass('Rosehana')
        Registrasi.InputPassConfirm('Rosehana')
        Registrasi.weakPass()
    })
    it('Mengisi field Password dengan medium password',()=>{
        Registrasi.InputFirstname('rosehana890')
        Registrasi.InputLastname('hanhandamdam')
        Registrasi.InputEmail('rosehana890@mailinator.com')
        Registrasi.InputPass('ROSEha12')
        Registrasi.InputPassConfirm('ROSEha12')
        Registrasi.mediumPass()
    })
    it('Mengisi field Password dengan verystrong password',()=>{
        Registrasi.InputFirstname('rosehana890')
        Registrasi.InputLastname('hanhandamdam')
        Registrasi.InputEmail('rosehana890@mailinator.com')
        Registrasi.InputPass('ROSEha12345@')
        Registrasi.InputPassConfirm('ROSEha12345@')
        Registrasi.strongPass()
    })
    it('Mengisi field konfimasi password dengan nilai yang berbeda',()=>{
        Registrasi.InputFirstname('rosehana890')
        Registrasi.InputLastname('hanhandamdam')
        Registrasi.InputEmail('rosehana890@mailinator.com')
        Registrasi.InputPass('ROSEhana123456')
        Registrasi.InputPassConfirm('ROSEha123')
        Registrasi.clickButtonReg()
        Registrasi.invalidPassconfirm()
    })
    it('Mengisi semua field dengan data yang sesuai',()=>{
        Registrasi.InputFirstname('rosehana89')
        Registrasi.InputFirstname('hanhandam')
        Registrasi.InputEmail('rosehana89@mailinator.com')
        Registrasi.InputPass('ROSEhana123456@') 
        Registrasi.InputPassConfirm('ROSEhana123456@')
        Registrasi.clickButtonReg()
        Registrasi.successReg()
    })
})