describe("Register test at Magento",()=> {
    beforeEach('akses page register magento', ()=>{
        cy.visit('https://magento.softwaretestingboard.com/customer/account/create/')
       })

    it('Mengosongkan semua field registrasi',()=>{
        cy.get('#firstname').clear()
        cy.get('#lastname').clear()
        cy.get('#email_address').clear()
        cy.get('#password').clear()
        cy.get('#password-confirmation').clear()
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#firstname-error').should('have.text', 'This is a required field.')
        cy.get('#lastname-error').should('have.text', 'This is a required field.')
        cy.get('#email_address-error').should('have.text', 'This is a required field.')
        cy.get('#password-error').should('have.text', 'This is a required field.')
        cy.get('#password-confirmation-error').should('have.text', 'This is a required field.')
    })
    it('Hanya mengisi first name',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').clear()
        cy.get('#email_address').clear()
        cy.get('#password').clear()
        cy.get('#password-confirmation').clear()
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#lastname-error').should('have.text', 'This is a required field.')
        cy.get('#email_address-error').should('have.text', 'This is a required field.')
        cy.get('#password-error').should('have.text', 'This is a required field.')
        cy.get('#password-confirmation-error').should('have.text', 'This is a required field.')
    })
    it('Hanya mengisi lastname',()=>{
        cy.get('#firstname').clear()
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').clear()
        cy.get('#password').clear()
        cy.get('#password-confirmation').clear()
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#firstname-error').should('have.text', 'This is a required field.')
        cy.get('#email_address-error').should('have.text', 'This is a required field.')
        cy.get('#password-error').should('have.text', 'This is a required field.')
        cy.get('#password-confirmation-error').should('have.text', 'This is a required field.')
    })
    it('Hanya mengisi email address',()=>{
        cy.get('#firstname').clear()
        cy.get('#lastname').clear()
        cy.get('#email_address').type('rosehana@mailinator.com')
        cy.get('#password').clear()
        cy.get('#password-confirmation').clear()
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#firstname-error').should('have.text', 'This is a required field.')
        cy.get('#lastname-error').should('have.text', 'This is a required field.')
        cy.get('#password-error').should('have.text', 'This is a required field.')
        cy.get('#password-confirmation-error').should('have.text', 'This is a required field.')
    })
    it('Hanya mengisi Password',()=>{
        cy.get('#firstname').clear()
        cy.get('#lastname').clear()
        cy.get('#email_address').clear()
        cy.get('#password').type('ROSEhana123')
        cy.get('#password-confirmation').clear()
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#firstname-error').should('have.text', 'This is a required field.')
        cy.get('#lastname-error').should('have.text', 'This is a required field.')
        cy.get('#email_address-error').should('have.text', 'This is a required field.')
        cy.get('#password-confirmation-error').should('have.text', 'This is a required field.')
    })
    it('Hanya mengisi field Konfirmasi password',()=>{
        cy.get('#firstname').clear()
        cy.get('#lastname').clear()
        cy.get('#email_address').clear()
        cy.get('#password').clear()
        cy.get('#password-confirmation').type('ROSEhana123')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#firstname-error').should('have.text', 'This is a required field.')
        cy.get('#lastname-error').should('have.text', 'This is a required field.')
        cy.get('#email_address-error').should('have.text', 'This is a required field.')
        cy.get('#password-error').should('have.text', 'This is a required field.')
    })
    it.only('User mengisi dengan invalid format email',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').type('rosehana')
        cy.get('#password').type('ROSEhana123456')
        cy.get('#password-confirmation').type('ROSEhana123456')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#email_address-error').should('have.text', 'Please enter a valid email address (Ex: johndoe@domain.com).')
    })
    it('User mengisi password kurang dari 8 digits',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').type('rosehana@mailinator.com')
        cy.get('#password').type('ROSEha')
        cy.get('#password-confirmation').type('ROSEha')
        //cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()  
        cy.get('#password-error').should('have.text', 'Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored.')
    })
    it('User input 8 digits lower case',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').type('rosehana@mailinator.com')
        cy.get('#password').type('rosehana')
        cy.get('#password-confirmation').type('rosehana')
        //cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#password-error').should('have.text', 'Minimum of different classes of characters in password is 3. Classes of characters: Lower Case, Upper Case, Digits, Special Characters.')   
    })
    it('User input 8 digits lower case dan uppercase',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').type('rosehana@mailinator.com')
        cy.get('#password').type('ROSEhana')
        cy.get('#password-confirmation').type('ROSEhana')
        //cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#password-error').should('have.text', 'Minimum of different classes of characters in password is 3. Classes of characters: Lower Case, Upper Case, Digits, Special Characters.') 
    })
    it('User input 10 digit lowercase, uppercase, dan digits',()=>{ 
       cy.get('#firstname').type('rosehana')
       cy.get('#lastname').type('damdam')
       cy.get('#email_address').type('rosehana@mailinator.com')
       cy.get('#password').type('ROSEhana123456')
       cy.get('#password-confirmation').type('ROSEhana123456')
        //cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click() // Belum melakukan cklik sudah memperoleh text Very Strong
       cy.get('#password-strength-meter-label').should('have.text','Very Strong')
    })
    it('User input 8 digit lowercase, uppercase, dan digits',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').type('rosehana@mailinator.com')
        cy.get('#password').type('ROSEha12')
        cy.get('#password-confirmation').type('ROSEha12')
        //cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()// Belum melakukan click sudah memperoleh text Medium
        cy.get('#password-strength-meter-label').should('have.text','Medium')
    })
    it('User input 6 digits uppercase, lowercase, dan digits',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').type('rosehana@mailinator.com')
        cy.get('#password').type('ROha12')
        cy.get('#password-confirmation').type('ROha12')
        //cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()// Belum melakukan klik ini user sudah memperoleh warning weak password
        cy.get('#password-strength-meter-label').should('have.text','Weak')
    })
    it('User input 6 digits uppercase, lowercase, dan digits dan klik button submit',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').type('rosehana@mailinator.com')
        cy.get('#password').type('ROha12')
        cy.get('#password-confirmation').type('ROha12')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#password-strength-meter-label').should('have.text','Weak')
    })
    it('Konfirmasi password tidak sesuai dengan actual password',()=>{
        cy.get('#firstname').type('rosehana')
        cy.get('#lastname').type('damdam')
        cy.get('#email_address').type('rosehana@mailinator.com')
        cy.get('#password').type('ROSEhana123456')
        cy.get('#password-confirmation').type('ROSEhana12345')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.get('#password-confirmation-error').should('have.text', 'Please enter the same value again.')
    })
    //it.only('Registrasi dengan data yang sesuai',()=>{
        //cy.get('#firstname').type('rosehana1')
        //cy.get('#lastname').type('damdam1')
        //cy.get('#email_address').type('rosehana1@mailinator.com')
        //cy.get('#password').type('ROSEhana123456')
        //cy.get('#password-confirmation').type('ROSEhana123456')
        //cy.get('.submit').click()
        //cy.get('.message-success > div').should('have.text', 'Thank you for registering with Main Website Store.')
    //}) 

})
